//import faker from 'faker'

export const dataTypes = {
  Category: [
    "Automotive",
    "Automotive Parts",
    "Automotive Tools",
    "Electronics / Cameras",
    "Automotive Accessories / Power",
    "Automotive / Power",
    "Automotive / Hand",
    "Automotive / Tires",
    "Baby / Bedding& Decor",
    "Baby / Nursing& Feeding Supplies",
    "Baby / Diapers& Wipes",
    "Baby / Health& Safety",
    "Baby / Walkers,Swings & Bouncers",
    "Books",
    "Clothing,Shoes & Accessories / Backpacks, Bags, Wallets & Accessories",
    "Electronics",
    "Electronics / Video Games",
    "Electronics / Batteries",
    "Electronics / Cameras",
    "Electronics / Computers",
    "Electronics / Digital",
    "Electronics / GPS& Navigation",
    "Electronics / Headphones& Portable Speakers",
    "Electronics / Computers ",
    "Electronics / Digital ",
    "Electronics / GPS& Navigation ",
    "Electronics / Headphones& Portable Speakers ",
    "Electronics / Home ",
    "Electronics / Portable ",
    "Electronics / Security& Surveillance ",
    "Electronics / Tablets& eReaders ",
    "Electronics / Printers,Scanners & Faxes ",
    "Electronics / Cellular ",
    "Electronics / Drones& Quadcopters ",
    "Electronics / Video Games / Consoles / Nintendo",
    "Electronics / Video Games / Consoles / Other",
    "Electronics / Video Games / Consoles / Microsoft",
    "Electronics / Video Games / Consoles / Sony",
    "Electronics / Video Games / Games / Microsoft",
    "Electronics / Video Games / Games / Nintendo",
    "Electronics / Video Games / Games / Other",
    "Electronics / Video Games / Games / Sony",
    "Electronics / Video Games / Accessories / Headsets / Virtual Reality Headsets",
    "Electronics / Video Games / Accessories / Headsets / Audio Headsets",
    "Electronics / Video Games / Accessories / Sensor Bars, Cameras & Kinects",
    "Toys / Learning & Education / Powered",
    "Toys / Learning & Education / Not Powered",
    "Toys / Instruments / Powered",
    "Toys / Instruments / Not Powered",
    "Home / Floor Care",
    "Home / Safes",
    "Electronics / Headphones & Portable Speakers / Accessories",
    "Electronics / GPS & Navigation / GPS Unit",
    "Electronics / GPS & Navigation / GPS Accessories",
    "Electronics / Computers / Portable Storage",
    "Music / Musical Instruments / Powered",
    "Music / Musical Instruments / Not Powered",
    "Sports, Fitness & Outdoors / Scooters, Skateboards & Skates / Powered",
    "Sports, Fitness & Outdoors / Scooters, Skateboards & Skates / Not Powered",
    "Home / Home Security & Safety",
    "Electronics / Printers, Scanners & Faxes / Ink, Toner, Accessories & Supplies",
    "Electronics / Cameras / Camcorders / Action Camcorders",
    "Electronics / Cameras / Camcorders / Digital Camcorders",
    "Electronics / Printers, Scanners & Faxes / Inkjet",
    "Electronics / Printers, Scanners & Faxes / Laser",
    "Electronics / Printers, Scanners & Faxes / All-In-One",
    "Electronics / Printers, Scanners & Faxes / Photo, Thermal & Dot Matrix",
    "Electronics / Video Games / Accessories / Batteries & Chargers",
    "Electronics / Video Games / Accessories / Cables & Adapters",
    "Electronics / Video Games / Accessories / Cases & Skins",
    "Electronics / Video Games / Accessories / Chairs",
    "Electronics / Video Games / Accessories / Controllers / Sony",
    "Electronics / Video Games / Accessories / Controllers / Microsoft",
    "Electronics / Video Games / Accessories / Controllers / Nintendo",
    "Electronics / Video Games / Accessories / Controllers / Other",
    "Electronics / Video Games / Accessories / Gaming Figures",
    "Electronics / Video Games / Accessories / Memory & Hard Drives",
    "Electronics / Video Games / Accessories / Stylus & Screen Protectors",
    "Home / Bedding / Sheets, Pillowcases & Bed Skirts",
    "Home / Bedding / Covers, Mattress Pads & Toppers",
    "Home / Bedding / Comforters & Duvets",
    "Home / Bedding / Pillows",
    "Home / Bedding / Bedding Sets",
    "Home / Bedding / Blankets, Throws & Quilts",
    "Office / Office Electronics / Binding Machines, Laminators",
    "Office / Office Electronics / Calculators",
    "Office / Office Electronics / Cash Registers",
    "Office / Office Electronics / Shredders",
    "Office / Office Electronics / Presentation Equipment",
    "Office / Office Electronics / Typewriters",
    "Patio & Garden / Gardening & Lawn Care / Accessories",
    "Patio & Garden / Gardening & Lawn Care / Hedge Clippers & Chainsaws",
    "Patio & Garden / Gardening & Lawn Care / Gardening Hand Tools",
    "Patio & Garden / Gardening & Lawn Care / Leaf Blowers & Vaccums",
    "Patio & Garden / Gardening & Lawn Care / Mowers",
    "Patio & Garden / Gardening & Lawn Care / Snow Removal",
    "Patio & Garden / Gardening & Lawn Care / Trimmers & Edgers",
    "Patio & Garden / Gardening & Lawn Care / Other",
    "Electronics / Wearable Technology / Accessories",
    "Electronics / Wearable Technology / Accessories / Samsung Gear",
    "Electronics / Wearable Technology / Accessories / Fitbit",
    "Electronics / Wearable Technology / Accessories / Other",
    "Electronics / Wearable Technology / Accessories / Apple Watch",
    "Jewelry",
    "Movies& TV Media",
    "Jewelry",
    "Movies& TV Media",
    "Music",
    "Office",
    "Pallets& Truckloads",
    "Party& Occasions",
    "Sports,Fitness & Outdoors"
  ],
  Warehouse: [
    "TRG-RO",
    "TRG-KY",
    "TRG-BV",
    "TRG-CANADA",
    "TRG-GS",
    "TRG-GA",
    "TRG-SK"
  ],
  "Date & Time": [
    "2019-01-02 11:44",
    "2019-02-11 12:24",
    "2019-03-23 13:10",
    "2019-04-02 9:44",
    "2019-05-10 8:44",
    "2019-06-02 7:10",
    "2019-07-04 9:44",
    "2019-08-02 12:44",
    "2018-09-32 13:10",
    "2018-10-02 9:22",
    "2018-11-02 7:45",
    "2018-12-05 12:16"
  ],
  Title: [
    "Apple MQUE2AM/A 3.3' Lightning to USB Cable - White",
    "NeotrixQI NW3 Magnetic Wireless Car Charger Mount",
    "Samsung 58' Class 4K (2160p) Smart LED TV (UN58NU7100FXZC)",
    "GoPro CHDHX-701 HERO7 Camcorder",
    "NeotrixQI NW3 Magnetic Wireless Car Charger Mount",
    "Blackweb Battery Case Sleeve for Samsung Galaxy S4 BWSGS4BLU Charge & sync",
    "JBL TUNE500BT Wireless On-Ear Headphones, Blue",
    "Rocketek RT-FCC22 2-socket Car Splitter Cigarette Lighter Adapter 12/24V 120W with 3.1A 2 USB Car Charger Adapter",
    "BL JBLCHARGE4BLKAM Charge 4 Portable Waterproof Wireless Bluetooth Speaker - Black",
    "Alpena 77277 Ezlink Exterior Bluetooth App Controlled Full RGB LED Light Strip Kit, 112-inch",
    "Garmin 010-01533-09 Drive 60 LM 6' USA & Canada Automotive Mountable GPS",
    "Tzumi 5761WM Sound Mates Bluetooth Earbuds with Protective Charging Case",
    "FUJIFILM Instax Mini Instant Film - 2 Packs Fujifilm INSTAX Mini film Twin Pack",
    "Vtech CS6124-21 Dect 6.0 2-Handset Cordless Phone System with Answering Machine",
    "Dell G5587-7835BLK G5 Gaming Laptop, 15.6-inch FHD (1920 x 1080), Intel Core i7-8750H, 16G, Licorice Black",
    "Samsung Galaxy Tab A 7.0' 8GB Black Wi-Fi SM-T280NZKAXAC",
    "GoPro CHDHX-701 HERO7 Camcorder - Black",
    "HP CC643WN#140 60 Tri-color Original Ink Cartridge",
    "Ubisoft Far Cry Primal (Xbox ONE) - Video Game",
    "Apple MPXK2LL/A Solo3 Wireless On-Ear Headphones, Brick Red",
    "Permatex Rain-X 79816 Weatherbeater Wiper Blade, Chlorinated Rubber"
  ],
  ID: [
    "52988944",
    "99330415",
    "75550734",
    "19559051",
    "19559051",
    "44344701",
    "78788672",
    "92819176",
    "49062278",
    "20314036",
    "26612545",
    "37324129",
    "42454727",
    "14758410",
    "62594444",
    "70312199",
    "17083666",
    "83264986",
    "81688960",
    "73915949",
    "92639085",
    "85423481",
    "12224020",
    "12224020",
    "47439303"
  ],
  UPC: [
    "52988944",
    "99330415",
    "75550734",
    "19559051",
    "19559051",
    "44344701",
    "78788672",
    "92819176",
    "49062278",
    "20314036",
    "26612545",
    "37324129",
    "42454727",
    "14758410",
    "62594444",
    "70312199",
    "17083666",
    "83264986",
    "81688960",
    "73915949",
    "92639085",
    "85423481",
    "12224020",
    "12224020",
    "47439303"
  ],
  "Sale Price": [
    "USD 327.00",
    "USD 117.00",
    "USD 997.56",
    "USD 997.00",
    "USD 224.00",
    "USD 121.21",
    "USD 933.00",
    "USD 997.00",
    "USD 443.00",
    "USD 965.00",
    "USD 997.11",
    "USD 465.78",
    "USD 923.03",
    "USD 997.00",
    "USD 47.00",
    "USD 191.00"
  ]
}
